version: '2.1'
volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  jenkins_data:

services:
 
  zap:
    image: owasp/zap2docker-stable
    container_name: zap
    command: zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true -config api.disablekey=true
    networks:
      - cicd
    expose:
      - 8080
    ports:
      - '8085:8080'

  
  myapp:
    image: jtux/spring-boot-demo
    container_name: myapp
    networks:
      - cicd
    expose:
      - 8080

networks:
  cicd:
    driver: bridge
